name: Modern Item Blocker
author: gjdunga
version: 3.0.5
description: |
  Blocks items, clothing and ammunition temporarily after a wipe or permanently until removed.
  Provides admin commands via chat, console (including RCON) and UI with configurable permissions.
language: C#
game: rust
license: MIT
