name: Modern Item Blocker
author: gjdunga
version: 4.1.1
description: |
  Blocks items, clothing, ammunition and deployables temporarily after a wipe or permanently until removed.
  Provides admin commands via chat, console (including RCON) with configurable permissions.
  Compatible with Oxide v2.0.7022+ and the Rust Naval Update.
language: C#
game: rust
license: MIT
tags:
  - items
  - administration
  - permissions
  - wipe
  - blocker
